# Generated by Django 4.0.7 on 2023-04-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-timestamp']},
        ),
    ]
