# Generated by Django 4.0.7 on 2023-04-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_alter_score_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='timestamp_active_upt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
