# Generated by Django 4.0.7 on 2023-04-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True)),
                ('retailer', models.CharField(max_length=100)),
                ('gluten_free', models.IntegerField(blank=True, null=True)),
                ('lactose_free', models.IntegerField(blank=True, null=True)),
                ('nut_free', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
