# Generated by Django 4.0.7 on 2023-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_groceryitem_similar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
