# Generated by Django 4.0.7 on 2023-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_alter_groceryitem_picture_alter_groceryitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='retailer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
