# Generated by Django 4.0.7 on 2023-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_alter_groceryitem_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='retailer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='similar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
