# Generated by Django 4.0.7 on 2023-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0008_alter_groceryitem_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
