# Generated by Django 4.0.7 on 2023-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0009_alter_groceryitem_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='picture',
            new_name='picture_file',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='picture_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
