# Generated by Django 4.0.7 on 2023-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0010_rename_picture_groceryitem_picture_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='picture_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
