# Generated by Django 4.0.7 on 2023-04-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0011_alter_groceryitem_picture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='picture_file',
        ),
    ]
