# Generated by Django 4.0.7 on 2023-04-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0012_remove_groceryitem_picture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='ingredients',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
