# Generated by Django 4.0.7 on 2023-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0013_alter_groceryitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='score_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='score_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
