# Generated by Django 4.0.7 on 2023-04-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0014_groceryitem_average_score_groceryitem_score_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='similar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
